services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - ../ssl:/app/ssl
      - ui_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    container_name: portfolio-frontend-dev

  frontend-prod:
    build: .
    ports:
      - "3000:80"
    container_name: portfolio-frontend-prod

volumes:
  ui_node_modules: