services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - .:/app
      - ui_node_modules:/app/node_modules

volumes:
  ui_node_modules: