services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - .:/app
      - ui_node_modules:/app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

volumes:
  ui_node_modules:
  backend_node_modules: