version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.prod
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

networks:
  default:
    driver: bridge